-- DROP TABLES
DROP TABLE IF EXISTS СOMMENTS;
DROP TABLE IF EXISTS BOOKINGS;
DROP TABLE IF EXISTS ITEMS;
DROP TABLE IF EXISTS USERS;

--CREATE TABLES
CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME     VARCHAR NOT NULL UNIQUE,
    EMAIL    VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ITEMS
(
    ITEM_ID     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    AVAILABLE   BOOLEAN,
    OWNER_ID    INTEGER NOT NULL,
    CONSTRAINT ITEMS_OWNER_ID_FK FOREIGN KEY (OWNER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BOOKINGS
(
    BOOKING_ID  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    START_DATE  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    END_DATE    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ITEM_ID     INTEGER NOT NULL,
    BOOKER_ID   INTEGER NOT NULL,
    STATUS      VARCHAR(20) NOT NULL,
    CONSTRAINT BOOKINGS_ITEM_ID_FK FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ITEM_ID) ON DELETE CASCADE,
    CONSTRAINT BOOKINGS_BOOKER_ID_FK FOREIGN KEY (BOOKER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS СOMMENTS
(
    СOMMENT_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEXT       VARCHAR NOT NULL,
    ITEM_ID    INTEGER NOT NULL,
    AUTHOR_ID  INTEGER NOT NULL,
    CREATED    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT СOMMENTS_ITEM_ID_FK FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ITEM_ID) ON DELETE CASCADE,
    CONSTRAINT СOMMENTS_AUTHOR_ID_FK FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);