-- DROP TABLES

DROP TABLE IF EXISTS KOMMENTS;
DROP TABLE IF EXISTS BOOKINGS;
DROP TABLE IF EXISTS ITEMS;
DROP TABLE IF EXISTS REQUESTS;
DROP TABLE IF EXISTS USERS;

--CREATE TABLES
CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME     VARCHAR(128) NOT NULL UNIQUE,
    EMAIL    VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS REQUESTS
(
    REQUEST_ID   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPTION  VARCHAR(512) NOT NULL,
    REQUESTER_ID INTEGER NOT NULL,
    CREATED      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT REQUESTS_REQUESTER_ID_FK FOREIGN KEY (REQUESTER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ITEMS
(
    ITEM_ID     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(258) NOT NULL,
    AVAILABLE   BOOLEAN,
    OWNER_ID    INTEGER NOT NULL,
    REQUEST_ID  INTEGER,
    CONSTRAINT ITEMS_OWNER_ID_FK FOREIGN KEY (OWNER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT ITEMS_REQUEST_ID_KR FOREIGN KEY (REQUEST_ID) REFERENCES REQUESTS(REQUEST_ID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS BOOKINGS
(
    BOOKING_ID  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    START_DATE  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    END_DATE    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ITEM_ID     INTEGER NOT NULL,
    BOOKER_ID   INTEGER NOT NULL,
    STATUS      VARCHAR(20) NOT NULL,
    CONSTRAINT BOOKINGS_ITEM_ID_FK FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ITEM_ID) ON DELETE CASCADE,
    CONSTRAINT BOOKINGS_BOOKER_ID_FK FOREIGN KEY (BOOKER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS KOMMENTS
(
    KOMMENT_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEXT       VARCHAR(512) NOT NULL,
    ITEM_ID    INTEGER NOT NULL,
    AUTHOR_ID  INTEGER NOT NULL,
    CREATED    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT KOMMENTS_ITEM_ID_FK FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ITEM_ID) ON DELETE CASCADE,
    CONSTRAINT KOMMENTS_AUTHOR_ID_FK FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);